name: "Install Python Dependencies"
description: "Installs Python Dependencies from cache or from PyPI if cache is not available.
Uses pyproject.toml and requirements-dev.txt as cache keys."
inputs:
  python-version:
    description: 'Which version of Python to use to run the tests.'
    required: true
    default: '3.8'
runs:
  using: "composite"
  steps:
    - name: "Install Cached Python Dependencies"
      uses: getsentry/action-setup-venv@v2.1.1
      id: venv
      with:
        python-version: ${{ inputs.python-version }}
        venv-dir: ${{ github.workspace }}/python_env
        cache-dependency-path: |
          tt_metal/python_env/requirements-dev.txt
          docs/requirements-docs.txt
          tests/sweep_framework/requirements-sweeps.txt
          pyproject.toml
          create_venv.sh
        install-cmd: ./create_venv.sh
