name: "(Blackhole) Blackhole nightly tests"

on:
  workflow_dispatch:
  # workflow_call:
  # schedule:
  #   - cron: "0 */6 * * *"

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  fd-nightly:
    needs: build-artifact
    uses: ./.github/workflows/blackhole-nightly-tests-impl.yaml
    secrets: inherit
