name: "[post-commit] Python wheels build and test"

on:
  workflow_dispatch:
    inputs:
      from-precompiled:
        description: "Use precompiled assets for wheel build"
        default: True
        type: boolean
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-artifact:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.from-precompiled }}
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  test-wheels:
    needs: build-artifact
    if: ${{ always() }}
    uses: ./.github/workflows/_test-wheels-impl.yaml
    with:
      from-precompiled: ${{ github.event_name == 'workflow_dispatch' && inputs.from-precompiled }}
