name: "(Single-card) Device perf regressions"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2,7,10,14,17,20,23 * * *"
  workflow_call:

jobs:
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      tracy: true
    secrets: inherit
  device-perf:
    needs: build-artifact-profiler
    secrets: inherit
    uses: ./.github/workflows/perf-device-models-impl.yaml
