name: "Create and Publish Release Docker Image"

on:
  workflow_dispatch:
jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-wheel: true
      version: "20.04"
  publish-release-image:
    needs: build-artifact
    uses: ./.github/workflows/publish-release-image.yaml
    secrets: inherit
    with:
      base-image: ${{ needs.build-artifact.outputs.ci-build-docker-image }}
      version: dev-${GITHUB_REF_NAME//\//-}
      is_major_version: false
