name: "[post-commit] metal - Run profiler regression"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      tracy: true
    secrets: inherit
  run-profiler-regression:
    needs: build-artifact-profiler
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/run-profiler-regression.yaml
    secrets: inherit
    with:
      arch: ${{ matrix.test-group.arch}}
      runner-label: ${{ matrix.test-group.runner-label}}
