name: "(TG) TG frequent tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *" # This cron schedule runs the workflow every 8 hours

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-wheel: true
  tg-frequent-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-frequent-tests-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.ci-build-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
