name: "(TGG) TGG unit tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *" # This cron schedule runs the workflow every 3 hours

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      version: "22.04"
      build-wheel: true
  TGG-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tgg-unit-tests-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.ci-build-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
